### ISSUE TITLE
pptx file upload error

### ISSUE THREAD

**Issue by kaakaa** [kaakaa/ppt-museum-webapp#15]
When i upload pptx file, occurs bellow error.

```
java.io.IOException: Error: End-of-File, expected line
        at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1110)
        at org.apache.pdfbox.pdfparser.COSParser.parseHeader(COSParser.java:1875)
        at org.apache.pdfbox.pdfparser.COSParser.parsePDFHeader(COSParser.java:1846)
        at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:242)
        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:973)
        at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:875)
        at org.kaakaa.pptmuseum.db.document.util.ThumbnailGenerater.generate(ThumbnailGenerater.java:26)
        at org.kaakaa.pptmuseum.db.document.util.SlideBuilder.buildThumbnailResource(SlideBuilder.java:89)
        at org.kaakaa.pptmuseum.db.document.util.SlideBuilder.buildPdfResource(SlideBuilder.java:69)
        at org.kaakaa.pptmuseum.db.document.util.SlideBuilder.buildPowerpointResource(SlideBuilder.java:80)
        at org.kaakaa.pptmuseum.db.document.util.RequestParser.parseMultipartItem(RequestParser.java:69)
        at org.kaakaa.pptmuseum.db.document.util.RequestParser.lambda$parse$5(RequestParser.java:23)
        at org.kaakaa.pptmuseum.db.document.util.RequestParser.lambda$parse$6(RequestParser.java:30)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at org.kaakaa.pptmuseum.db.document.util.RequestParser.parse(RequestParser.java:30)
        at org.kaakaa.pptmuseum.event.db.slide.UploadSlide.execute(UploadSlide.java:37)
        at org.kaakaa.pptmuseum.event.EventExecuter.execute(EventExecuter.java:11)
        at org.kaakaa.pptmuseum.Main.lambda$main$12(Main.java:44)
        at spark.RouteImpl$1.handle(RouteImpl.java:58)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by kaakaa** [comment]
Maybe it's caused by powerpoint 2016...

**Comment by kaakaa** [comment]
This issue is disscussed in follow.
[pptx file upload error · Issue #9 · kaakaa/ppt-museum](https://github.com/kaakaa/ppt-museum/issues/9)
